# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ali/cvflow_cnngen_samples_1.6/library/eazyai

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ali/cvflow_cnngen_samples_1.6/library/eazyai/unit_test

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ali/cvflow_cnngen_samples_1.6/library/eazyai/unit_test/CMakeFiles /home/ali/cvflow_cnngen_samples_1.6/library/eazyai/unit_test/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ali/cvflow_cnngen_samples_1.6/library/eazyai/unit_test/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named eazyai

# Build rule for target.
eazyai: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 eazyai
.PHONY : eazyai

# fast build rule for target.
eazyai/fast:
	$(MAKE) -f CMakeFiles/eazyai.dir/build.make CMakeFiles/eazyai.dir/build
.PHONY : eazyai/fast

src/comm/ea_queue.o: src/comm/ea_queue.c.o

.PHONY : src/comm/ea_queue.o

# target to build an object file
src/comm/ea_queue.c.o:
	$(MAKE) -f CMakeFiles/eazyai.dir/build.make CMakeFiles/eazyai.dir/src/comm/ea_queue.c.o
.PHONY : src/comm/ea_queue.c.o

src/comm/ea_queue.i: src/comm/ea_queue.c.i

.PHONY : src/comm/ea_queue.i

# target to preprocess a source file
src/comm/ea_queue.c.i:
	$(MAKE) -f CMakeFiles/eazyai.dir/build.make CMakeFiles/eazyai.dir/src/comm/ea_queue.c.i
.PHONY : src/comm/ea_queue.c.i

src/comm/ea_queue.s: src/comm/ea_queue.c.s

.PHONY : src/comm/ea_queue.s

# target to generate assembly for a file
src/comm/ea_queue.c.s:
	$(MAKE) -f CMakeFiles/eazyai.dir/build.make CMakeFiles/eazyai.dir/src/comm/ea_queue.c.s
.PHONY : src/comm/ea_queue.c.s

src/simulator/acinf_api.o: src/simulator/acinf_api.cpp.o

.PHONY : src/simulator/acinf_api.o

# target to build an object file
src/simulator/acinf_api.cpp.o:
	$(MAKE) -f CMakeFiles/eazyai.dir/build.make CMakeFiles/eazyai.dir/src/simulator/acinf_api.cpp.o
.PHONY : src/simulator/acinf_api.cpp.o

src/simulator/acinf_api.i: src/simulator/acinf_api.cpp.i

.PHONY : src/simulator/acinf_api.i

# target to preprocess a source file
src/simulator/acinf_api.cpp.i:
	$(MAKE) -f CMakeFiles/eazyai.dir/build.make CMakeFiles/eazyai.dir/src/simulator/acinf_api.cpp.i
.PHONY : src/simulator/acinf_api.cpp.i

src/simulator/acinf_api.s: src/simulator/acinf_api.cpp.s

.PHONY : src/simulator/acinf_api.s

# target to generate assembly for a file
src/simulator/acinf_api.cpp.s:
	$(MAKE) -f CMakeFiles/eazyai.dir/build.make CMakeFiles/eazyai.dir/src/simulator/acinf_api.cpp.s
.PHONY : src/simulator/acinf_api.cpp.s

src/simulator/ades_api.o: src/simulator/ades_api.cpp.o

.PHONY : src/simulator/ades_api.o

# target to build an object file
src/simulator/ades_api.cpp.o:
	$(MAKE) -f CMakeFiles/eazyai.dir/build.make CMakeFiles/eazyai.dir/src/simulator/ades_api.cpp.o
.PHONY : src/simulator/ades_api.cpp.o

src/simulator/ades_api.i: src/simulator/ades_api.cpp.i

.PHONY : src/simulator/ades_api.i

# target to preprocess a source file
src/simulator/ades_api.cpp.i:
	$(MAKE) -f CMakeFiles/eazyai.dir/build.make CMakeFiles/eazyai.dir/src/simulator/ades_api.cpp.i
.PHONY : src/simulator/ades_api.cpp.i

src/simulator/ades_api.s: src/simulator/ades_api.cpp.s

.PHONY : src/simulator/ades_api.s

# target to generate assembly for a file
src/simulator/ades_api.cpp.s:
	$(MAKE) -f CMakeFiles/eazyai.dir/build.make CMakeFiles/eazyai.dir/src/simulator/ades_api.cpp.s
.PHONY : src/simulator/ades_api.cpp.s

src/simulator/ea_display.o: src/simulator/ea_display.c.o

.PHONY : src/simulator/ea_display.o

# target to build an object file
src/simulator/ea_display.c.o:
	$(MAKE) -f CMakeFiles/eazyai.dir/build.make CMakeFiles/eazyai.dir/src/simulator/ea_display.c.o
.PHONY : src/simulator/ea_display.c.o

src/simulator/ea_display.i: src/simulator/ea_display.c.i

.PHONY : src/simulator/ea_display.i

# target to preprocess a source file
src/simulator/ea_display.c.i:
	$(MAKE) -f CMakeFiles/eazyai.dir/build.make CMakeFiles/eazyai.dir/src/simulator/ea_display.c.i
.PHONY : src/simulator/ea_display.c.i

src/simulator/ea_display.s: src/simulator/ea_display.c.s

.PHONY : src/simulator/ea_display.s

# target to generate assembly for a file
src/simulator/ea_display.c.s:
	$(MAKE) -f CMakeFiles/eazyai.dir/build.make CMakeFiles/eazyai.dir/src/simulator/ea_display.c.s
.PHONY : src/simulator/ea_display.c.s

src/simulator/ea_env.o: src/simulator/ea_env.c.o

.PHONY : src/simulator/ea_env.o

# target to build an object file
src/simulator/ea_env.c.o:
	$(MAKE) -f CMakeFiles/eazyai.dir/build.make CMakeFiles/eazyai.dir/src/simulator/ea_env.c.o
.PHONY : src/simulator/ea_env.c.o

src/simulator/ea_env.i: src/simulator/ea_env.c.i

.PHONY : src/simulator/ea_env.i

# target to preprocess a source file
src/simulator/ea_env.c.i:
	$(MAKE) -f CMakeFiles/eazyai.dir/build.make CMakeFiles/eazyai.dir/src/simulator/ea_env.c.i
.PHONY : src/simulator/ea_env.c.i

src/simulator/ea_env.s: src/simulator/ea_env.c.s

.PHONY : src/simulator/ea_env.s

# target to generate assembly for a file
src/simulator/ea_env.c.s:
	$(MAKE) -f CMakeFiles/eazyai.dir/build.make CMakeFiles/eazyai.dir/src/simulator/ea_env.c.s
.PHONY : src/simulator/ea_env.c.s

src/simulator/ea_img_resource.o: src/simulator/ea_img_resource.c.o

.PHONY : src/simulator/ea_img_resource.o

# target to build an object file
src/simulator/ea_img_resource.c.o:
	$(MAKE) -f CMakeFiles/eazyai.dir/build.make CMakeFiles/eazyai.dir/src/simulator/ea_img_resource.c.o
.PHONY : src/simulator/ea_img_resource.c.o

src/simulator/ea_img_resource.i: src/simulator/ea_img_resource.c.i

.PHONY : src/simulator/ea_img_resource.i

# target to preprocess a source file
src/simulator/ea_img_resource.c.i:
	$(MAKE) -f CMakeFiles/eazyai.dir/build.make CMakeFiles/eazyai.dir/src/simulator/ea_img_resource.c.i
.PHONY : src/simulator/ea_img_resource.c.i

src/simulator/ea_img_resource.s: src/simulator/ea_img_resource.c.s

.PHONY : src/simulator/ea_img_resource.s

# target to generate assembly for a file
src/simulator/ea_img_resource.c.s:
	$(MAKE) -f CMakeFiles/eazyai.dir/build.make CMakeFiles/eazyai.dir/src/simulator/ea_img_resource.c.s
.PHONY : src/simulator/ea_img_resource.c.s

src/simulator/ea_log.o: src/simulator/ea_log.c.o

.PHONY : src/simulator/ea_log.o

# target to build an object file
src/simulator/ea_log.c.o:
	$(MAKE) -f CMakeFiles/eazyai.dir/build.make CMakeFiles/eazyai.dir/src/simulator/ea_log.c.o
.PHONY : src/simulator/ea_log.c.o

src/simulator/ea_log.i: src/simulator/ea_log.c.i

.PHONY : src/simulator/ea_log.i

# target to preprocess a source file
src/simulator/ea_log.c.i:
	$(MAKE) -f CMakeFiles/eazyai.dir/build.make CMakeFiles/eazyai.dir/src/simulator/ea_log.c.i
.PHONY : src/simulator/ea_log.c.i

src/simulator/ea_log.s: src/simulator/ea_log.c.s

.PHONY : src/simulator/ea_log.s

# target to generate assembly for a file
src/simulator/ea_log.c.s:
	$(MAKE) -f CMakeFiles/eazyai.dir/build.make CMakeFiles/eazyai.dir/src/simulator/ea_log.c.s
.PHONY : src/simulator/ea_log.c.s

src/simulator/ea_net.o: src/simulator/ea_net.c.o

.PHONY : src/simulator/ea_net.o

# target to build an object file
src/simulator/ea_net.c.o:
	$(MAKE) -f CMakeFiles/eazyai.dir/build.make CMakeFiles/eazyai.dir/src/simulator/ea_net.c.o
.PHONY : src/simulator/ea_net.c.o

src/simulator/ea_net.i: src/simulator/ea_net.c.i

.PHONY : src/simulator/ea_net.i

# target to preprocess a source file
src/simulator/ea_net.c.i:
	$(MAKE) -f CMakeFiles/eazyai.dir/build.make CMakeFiles/eazyai.dir/src/simulator/ea_net.c.i
.PHONY : src/simulator/ea_net.c.i

src/simulator/ea_net.s: src/simulator/ea_net.c.s

.PHONY : src/simulator/ea_net.s

# target to generate assembly for a file
src/simulator/ea_net.c.s:
	$(MAKE) -f CMakeFiles/eazyai.dir/build.make CMakeFiles/eazyai.dir/src/simulator/ea_net.c.s
.PHONY : src/simulator/ea_net.c.s

src/simulator/ea_preprocess.o: src/simulator/ea_preprocess.c.o

.PHONY : src/simulator/ea_preprocess.o

# target to build an object file
src/simulator/ea_preprocess.c.o:
	$(MAKE) -f CMakeFiles/eazyai.dir/build.make CMakeFiles/eazyai.dir/src/simulator/ea_preprocess.c.o
.PHONY : src/simulator/ea_preprocess.c.o

src/simulator/ea_preprocess.i: src/simulator/ea_preprocess.c.i

.PHONY : src/simulator/ea_preprocess.i

# target to preprocess a source file
src/simulator/ea_preprocess.c.i:
	$(MAKE) -f CMakeFiles/eazyai.dir/build.make CMakeFiles/eazyai.dir/src/simulator/ea_preprocess.c.i
.PHONY : src/simulator/ea_preprocess.c.i

src/simulator/ea_preprocess.s: src/simulator/ea_preprocess.c.s

.PHONY : src/simulator/ea_preprocess.s

# target to generate assembly for a file
src/simulator/ea_preprocess.c.s:
	$(MAKE) -f CMakeFiles/eazyai.dir/build.make CMakeFiles/eazyai.dir/src/simulator/ea_preprocess.c.s
.PHONY : src/simulator/ea_preprocess.c.s

src/simulator/ea_tensor.o: src/simulator/ea_tensor.c.o

.PHONY : src/simulator/ea_tensor.o

# target to build an object file
src/simulator/ea_tensor.c.o:
	$(MAKE) -f CMakeFiles/eazyai.dir/build.make CMakeFiles/eazyai.dir/src/simulator/ea_tensor.c.o
.PHONY : src/simulator/ea_tensor.c.o

src/simulator/ea_tensor.i: src/simulator/ea_tensor.c.i

.PHONY : src/simulator/ea_tensor.i

# target to preprocess a source file
src/simulator/ea_tensor.c.i:
	$(MAKE) -f CMakeFiles/eazyai.dir/build.make CMakeFiles/eazyai.dir/src/simulator/ea_tensor.c.i
.PHONY : src/simulator/ea_tensor.c.i

src/simulator/ea_tensor.s: src/simulator/ea_tensor.c.s

.PHONY : src/simulator/ea_tensor.s

# target to generate assembly for a file
src/simulator/ea_tensor.c.s:
	$(MAKE) -f CMakeFiles/eazyai.dir/build.make CMakeFiles/eazyai.dir/src/simulator/ea_tensor.c.s
.PHONY : src/simulator/ea_tensor.c.s

src/simulator/preprocess_cpu.o: src/simulator/preprocess_cpu.c.o

.PHONY : src/simulator/preprocess_cpu.o

# target to build an object file
src/simulator/preprocess_cpu.c.o:
	$(MAKE) -f CMakeFiles/eazyai.dir/build.make CMakeFiles/eazyai.dir/src/simulator/preprocess_cpu.c.o
.PHONY : src/simulator/preprocess_cpu.c.o

src/simulator/preprocess_cpu.i: src/simulator/preprocess_cpu.c.i

.PHONY : src/simulator/preprocess_cpu.i

# target to preprocess a source file
src/simulator/preprocess_cpu.c.i:
	$(MAKE) -f CMakeFiles/eazyai.dir/build.make CMakeFiles/eazyai.dir/src/simulator/preprocess_cpu.c.i
.PHONY : src/simulator/preprocess_cpu.c.i

src/simulator/preprocess_cpu.s: src/simulator/preprocess_cpu.c.s

.PHONY : src/simulator/preprocess_cpu.s

# target to generate assembly for a file
src/simulator/preprocess_cpu.c.s:
	$(MAKE) -f CMakeFiles/eazyai.dir/build.make CMakeFiles/eazyai.dir/src/simulator/preprocess_cpu.c.s
.PHONY : src/simulator/preprocess_cpu.c.s

src/utils/display_256_colors_table.o: src/utils/display_256_colors_table.c.o

.PHONY : src/utils/display_256_colors_table.o

# target to build an object file
src/utils/display_256_colors_table.c.o:
	$(MAKE) -f CMakeFiles/eazyai.dir/build.make CMakeFiles/eazyai.dir/src/utils/display_256_colors_table.c.o
.PHONY : src/utils/display_256_colors_table.c.o

src/utils/display_256_colors_table.i: src/utils/display_256_colors_table.c.i

.PHONY : src/utils/display_256_colors_table.i

# target to preprocess a source file
src/utils/display_256_colors_table.c.i:
	$(MAKE) -f CMakeFiles/eazyai.dir/build.make CMakeFiles/eazyai.dir/src/utils/display_256_colors_table.c.i
.PHONY : src/utils/display_256_colors_table.c.i

src/utils/display_256_colors_table.s: src/utils/display_256_colors_table.c.s

.PHONY : src/utils/display_256_colors_table.s

# target to generate assembly for a file
src/utils/display_256_colors_table.c.s:
	$(MAKE) -f CMakeFiles/eazyai.dir/build.make CMakeFiles/eazyai.dir/src/utils/display_256_colors_table.c.s
.PHONY : src/utils/display_256_colors_table.c.s

src/utils/display_jpeg.o: src/utils/display_jpeg.c.o

.PHONY : src/utils/display_jpeg.o

# target to build an object file
src/utils/display_jpeg.c.o:
	$(MAKE) -f CMakeFiles/eazyai.dir/build.make CMakeFiles/eazyai.dir/src/utils/display_jpeg.c.o
.PHONY : src/utils/display_jpeg.c.o

src/utils/display_jpeg.i: src/utils/display_jpeg.c.i

.PHONY : src/utils/display_jpeg.i

# target to preprocess a source file
src/utils/display_jpeg.c.i:
	$(MAKE) -f CMakeFiles/eazyai.dir/build.make CMakeFiles/eazyai.dir/src/utils/display_jpeg.c.i
.PHONY : src/utils/display_jpeg.c.i

src/utils/display_jpeg.s: src/utils/display_jpeg.c.s

.PHONY : src/utils/display_jpeg.s

# target to generate assembly for a file
src/utils/display_jpeg.c.s:
	$(MAKE) -f CMakeFiles/eazyai.dir/build.make CMakeFiles/eazyai.dir/src/utils/display_jpeg.c.s
.PHONY : src/utils/display_jpeg.c.s

src/utils/ea_utils.o: src/utils/ea_utils.c.o

.PHONY : src/utils/ea_utils.o

# target to build an object file
src/utils/ea_utils.c.o:
	$(MAKE) -f CMakeFiles/eazyai.dir/build.make CMakeFiles/eazyai.dir/src/utils/ea_utils.c.o
.PHONY : src/utils/ea_utils.c.o

src/utils/ea_utils.i: src/utils/ea_utils.c.i

.PHONY : src/utils/ea_utils.i

# target to preprocess a source file
src/utils/ea_utils.c.i:
	$(MAKE) -f CMakeFiles/eazyai.dir/build.make CMakeFiles/eazyai.dir/src/utils/ea_utils.c.i
.PHONY : src/utils/ea_utils.c.i

src/utils/ea_utils.s: src/utils/ea_utils.c.s

.PHONY : src/utils/ea_utils.s

# target to generate assembly for a file
src/utils/ea_utils.c.s:
	$(MAKE) -f CMakeFiles/eazyai.dir/build.make CMakeFiles/eazyai.dir/src/utils/ea_utils.c.s
.PHONY : src/utils/ea_utils.c.s

src/utils/env_callbacks.o: src/utils/env_callbacks.cpp.o

.PHONY : src/utils/env_callbacks.o

# target to build an object file
src/utils/env_callbacks.cpp.o:
	$(MAKE) -f CMakeFiles/eazyai.dir/build.make CMakeFiles/eazyai.dir/src/utils/env_callbacks.cpp.o
.PHONY : src/utils/env_callbacks.cpp.o

src/utils/env_callbacks.i: src/utils/env_callbacks.cpp.i

.PHONY : src/utils/env_callbacks.i

# target to preprocess a source file
src/utils/env_callbacks.cpp.i:
	$(MAKE) -f CMakeFiles/eazyai.dir/build.make CMakeFiles/eazyai.dir/src/utils/env_callbacks.cpp.i
.PHONY : src/utils/env_callbacks.cpp.i

src/utils/env_callbacks.s: src/utils/env_callbacks.cpp.s

.PHONY : src/utils/env_callbacks.s

# target to generate assembly for a file
src/utils/env_callbacks.cpp.s:
	$(MAKE) -f CMakeFiles/eazyai.dir/build.make CMakeFiles/eazyai.dir/src/utils/env_callbacks.cpp.s
.PHONY : src/utils/env_callbacks.cpp.s

src/utils/opencv_utils.o: src/utils/opencv_utils.cpp.o

.PHONY : src/utils/opencv_utils.o

# target to build an object file
src/utils/opencv_utils.cpp.o:
	$(MAKE) -f CMakeFiles/eazyai.dir/build.make CMakeFiles/eazyai.dir/src/utils/opencv_utils.cpp.o
.PHONY : src/utils/opencv_utils.cpp.o

src/utils/opencv_utils.i: src/utils/opencv_utils.cpp.i

.PHONY : src/utils/opencv_utils.i

# target to preprocess a source file
src/utils/opencv_utils.cpp.i:
	$(MAKE) -f CMakeFiles/eazyai.dir/build.make CMakeFiles/eazyai.dir/src/utils/opencv_utils.cpp.i
.PHONY : src/utils/opencv_utils.cpp.i

src/utils/opencv_utils.s: src/utils/opencv_utils.cpp.s

.PHONY : src/utils/opencv_utils.s

# target to generate assembly for a file
src/utils/opencv_utils.cpp.s:
	$(MAKE) -f CMakeFiles/eazyai.dir/build.make CMakeFiles/eazyai.dir/src/utils/opencv_utils.cpp.s
.PHONY : src/utils/opencv_utils.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... install/local"
	@echo "... eazyai"
	@echo "... src/comm/ea_queue.o"
	@echo "... src/comm/ea_queue.i"
	@echo "... src/comm/ea_queue.s"
	@echo "... src/simulator/acinf_api.o"
	@echo "... src/simulator/acinf_api.i"
	@echo "... src/simulator/acinf_api.s"
	@echo "... src/simulator/ades_api.o"
	@echo "... src/simulator/ades_api.i"
	@echo "... src/simulator/ades_api.s"
	@echo "... src/simulator/ea_display.o"
	@echo "... src/simulator/ea_display.i"
	@echo "... src/simulator/ea_display.s"
	@echo "... src/simulator/ea_env.o"
	@echo "... src/simulator/ea_env.i"
	@echo "... src/simulator/ea_env.s"
	@echo "... src/simulator/ea_img_resource.o"
	@echo "... src/simulator/ea_img_resource.i"
	@echo "... src/simulator/ea_img_resource.s"
	@echo "... src/simulator/ea_log.o"
	@echo "... src/simulator/ea_log.i"
	@echo "... src/simulator/ea_log.s"
	@echo "... src/simulator/ea_net.o"
	@echo "... src/simulator/ea_net.i"
	@echo "... src/simulator/ea_net.s"
	@echo "... src/simulator/ea_preprocess.o"
	@echo "... src/simulator/ea_preprocess.i"
	@echo "... src/simulator/ea_preprocess.s"
	@echo "... src/simulator/ea_tensor.o"
	@echo "... src/simulator/ea_tensor.i"
	@echo "... src/simulator/ea_tensor.s"
	@echo "... src/simulator/preprocess_cpu.o"
	@echo "... src/simulator/preprocess_cpu.i"
	@echo "... src/simulator/preprocess_cpu.s"
	@echo "... src/utils/display_256_colors_table.o"
	@echo "... src/utils/display_256_colors_table.i"
	@echo "... src/utils/display_256_colors_table.s"
	@echo "... src/utils/display_jpeg.o"
	@echo "... src/utils/display_jpeg.i"
	@echo "... src/utils/display_jpeg.s"
	@echo "... src/utils/ea_utils.o"
	@echo "... src/utils/ea_utils.i"
	@echo "... src/utils/ea_utils.s"
	@echo "... src/utils/env_callbacks.o"
	@echo "... src/utils/env_callbacks.i"
	@echo "... src/utils/env_callbacks.s"
	@echo "... src/utils/opencv_utils.o"
	@echo "... src/utils/opencv_utils.i"
	@echo "... src/utils/opencv_utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

